version: "3.9"

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_container
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
      - ./pad_debug.txt:/app/pad_debug.txt
      - ./output_with_bot_replies.json:/app/output_with_bot_replies.json
      - ./data.json:/app/data.json
